// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX_8236VrX0Yt9JLZSHN_i4ydpNXtnuNc',
    appId: '1:490571494723:web:782d2472d76e2033e1ebf6',
    messagingSenderId: '490571494723',
    projectId: 'medical-translator-project',
    authDomain: 'medical-translator-project.firebaseapp.com',
    storageBucket: 'medical-translator-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsSIKIn57kq7wk_v0jra0FAONksUua6SU',
    appId: '1:490571494723:android:64b473e97ff306d0e1ebf6',
    messagingSenderId: '490571494723',
    projectId: 'medical-translator-project',
    storageBucket: 'medical-translator-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19aW75mINIHGyFY7p-AGB3xmida2t7Qk',
    appId: '1:490571494723:ios:0681096756902855e1ebf6',
    messagingSenderId: '490571494723',
    projectId: 'medical-translator-project',
    storageBucket: 'medical-translator-project.firebasestorage.app',
    iosBundleId: 'com.example.medicalTranslatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19aW75mINIHGyFY7p-AGB3xmida2t7Qk',
    appId: '1:490571494723:ios:0681096756902855e1ebf6',
    messagingSenderId: '490571494723',
    projectId: 'medical-translator-project',
    storageBucket: 'medical-translator-project.firebasestorage.app',
    iosBundleId: 'com.example.medicalTranslatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX_8236VrX0Yt9JLZSHN_i4ydpNXtnuNc',
    appId: '1:490571494723:web:c0059fe2d82fea96e1ebf6',
    messagingSenderId: '490571494723',
    projectId: 'medical-translator-project',
    authDomain: 'medical-translator-project.firebaseapp.com',
    storageBucket: 'medical-translator-project.firebasestorage.app',
  );

}