org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=20
unityProjectPath=C:/Users/DELL/Final
unity.projectPath=C:/Users/DELL/Final
unity.debugSymbolLevel=none
unity.buildToolsVersion=34.0.0
unity.minSdkVersion=24
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.tejas.indoor_navigation
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=0.1
unity.namespace=com.tejas.indoor_navigation
unity.agpVersion=8.7.2
unity.androidSdkPath=D:/unity/6000.2.7f2/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=D:/unity/6000.2.7f2/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=D:/unity/6000.2.7f2/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never
flutter.hostAppProjectName=launcher